spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    username: weather_batch
    password: 0wc3lbmu
    platform: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2

  batch:
    initialize-schema: always

  liquibase:
    liquibase-schema: public